CREATE DATABASE IF NOT EXISTS mockfolio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mockfolio;

CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, is_admin BOOLEAN NOT NULL DEFAULT FALSE, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX ix_users_username (username), INDEX ix_users_email (email)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS accounts (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL UNIQUE, cash_balance DECIMAL(16,2) NOT NULL DEFAULT 100000.00, starting_balance DECIMAL(16,2) NOT NULL DEFAULT 100000.00, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT ck_accounts_cash CHECK (cash_balance >= 0)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS stocks (id INT AUTO_INCREMENT PRIMARY KEY, symbol VARCHAR(20) NOT NULL UNIQUE, company_name VARCHAR(120) NOT NULL, sector VARCHAR(80) NOT NULL, reference_price DECIMAL(16,2) NOT NULL, simulated_price DECIMAL(16,2) NOT NULL, previous_simulated_price DECIMAL(16,2) NOT NULL, average_daily_volume INT NOT NULL, volatility DECIMAL(8,4) NOT NULL DEFAULT 0.0200, is_active BOOLEAN NOT NULL DEFAULT TRUE, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX ix_stocks_symbol (symbol)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS holdings (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, stock_id INT NOT NULL, quantity INT NOT NULL, average_buy_price DECIMAL(16,2) NOT NULL, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_holdings_user_stock (user_id, stock_id), CONSTRAINT fk_holdings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_holdings_stock FOREIGN KEY (stock_id) REFERENCES stocks(id), CONSTRAINT ck_holdings_quantity CHECK (quantity > 0), INDEX ix_holdings_user_stock (user_id, stock_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS orders (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, stock_id INT NOT NULL, order_type ENUM('BUY','SELL') NOT NULL, quantity INT NOT NULL, requested_price DECIMAL(16,2) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'FILLED', client_order_key VARCHAR(80) UNIQUE, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_orders_stock FOREIGN KEY (stock_id) REFERENCES stocks(id), INDEX ix_orders_user (user_id), INDEX ix_orders_stock (stock_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS trades (id INT AUTO_INCREMENT PRIMARY KEY, order_id INT NOT NULL UNIQUE, user_id INT NOT NULL, stock_id INT NOT NULL, side ENUM('BUY','SELL') NOT NULL, quantity INT NOT NULL, fill_price DECIMAL(16,2) NOT NULL, brokerage DECIMAL(16,2) NOT NULL, price_before DECIMAL(16,2) NOT NULL, price_after DECIMAL(16,2) NOT NULL, price_impact DECIMAL(16,2) NOT NULL, deviation_after_trade DECIMAL(16,2) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_trades_order FOREIGN KEY (order_id) REFERENCES orders(id), CONSTRAINT fk_trades_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_trades_stock FOREIGN KEY (stock_id) REFERENCES stocks(id), INDEX ix_trades_user (user_id), INDEX ix_trades_stock (stock_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS price_history (id INT AUTO_INCREMENT PRIMARY KEY, stock_id INT NOT NULL, reference_price DECIMAL(16,2) NOT NULL, simulated_price DECIMAL(16,2) NOT NULL, deviation DECIMAL(16,2) NOT NULL, deviation_percentage DECIMAL(8,4) NOT NULL, recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_history_stock FOREIGN KEY (stock_id) REFERENCES stocks(id) ON DELETE CASCADE, INDEX ix_history_stock_time (stock_id, recorded_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS watchlist (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, stock_id INT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_watchlist_user_stock (user_id, stock_id), CONSTRAINT fk_watch_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_watch_stock FOREIGN KEY (stock_id) REFERENCES stocks(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_log (id INT AUTO_INCREMENT PRIMARY KEY, action VARCHAR(40) NOT NULL, table_name VARCHAR(50) NOT NULL, record_id INT NOT NULL, old_value TEXT, new_value TEXT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
